### ISSUE TITLE
Server does not appear on serverlist

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-issues#1802]
### Description of the problem

I have a server running on linux. I can direct connect to the server but the server does not appear on the serverlist.

### Reproduction steps

My server.toml:

```toml
name = "Plus1 Roleplay DEV Main Branch"
host = "0.0.0.0"
port = 7788
debug = true
players = 128
password = "beta"
announce = true
token = "PRIVATE"
gamemode = "Roleplay"
website = "plusonerp.eu"
language = "de"
sendPlayerNames = false
earlyAuthUrl = "https://earlyauth.plusonerp.eu"
useEarlyAuth = true
description = "Development Server der Main Branch"
modules = ["js-module", "js-bytecode-module", "csharp-module"]
resources = [
        "client-package",
        "server-package",
        "chat"
]
```

### Expected behaviour

The server should appear on the list.

### Operating system

Debian 11

### Version

release 14.9

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version
