### ISSUE TITLE
Add environment option to server.toml

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2163]
### Description of the problem

Add a new string option called `environment` to `server.toml` which is accessible on the server and client side [Variables](https://docs.altv.mp/js/api/alt-server.html#variables).
```toml
environment = 'dev'
environment = 'production'
```

### Desired solution for the problem

Like [version](https://docs.altv.mp/js/api/alt-client.html#_altmp_altv_types_alt_client_version) option.
