### ISSUE TITLE
Disable log

### ISSUE THREAD

**Issue by tommydusty** [altmp/altv-issues#2287]
### Description of the problem

As `Yiin` said in Discord, it's better to add two variables in order to disable the log on both sides (client and server's `toml` file).
```toml
enableSystemLogs = true
enableInternalLogs = true
```
![565584582](https://github.com/altmp/altv-issues/assets/168000671/bc0e6da2-f3b2-4df8-833e-d52de8271129)

### Desired solution for the problem

Empty

### Alternatives you considered

Empty

### Additional context

Empty
