### ISSUE TITLE
Loading multiple rpf files in one resource

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2335]
### Description of the problem

Instead of creating multiple resources for each `rpf` file, it's a good idea to support multiple `rpf` files in a single resource.

### Desired solution for the problem

```toml
# resource.toml
type = 'rpf'

# Absolute path
rpf-files = [
    'dlc1.rpf',
    'archive/dlc2.rpf',
    'archive/dlc3.rpf'
]
```
```toml
# resource.toml
type = 'rpf'

# Wildcard
rpf-files = [
    'archive/*'
]
```

### Alternatives you considered

No

### Additional context

No
